### ISSUE TITLE
[Feature request] Set default folder and download only audio option

### ISSUE THREAD

**Issue by NewVicious** [anidl/crunchyroll-downloader-nx#17]
Hello,
Is possible to add in the Filename Template the option to make a folder whit the show name?
and add argument to download only the audio file?
I am very interested in those 2 options since with the first when I download several series I have to move all the episodes in their respective folder and with the 2nd so as not to have to download the entire episode again to extract the audio.

**Comment by anidl** [comment]
folder added in 4.19
https://github.com/anidl/crunchyroll-downloader-nx/releases/tag/4.19.0
download only audio not possible, crunchyroll don't have audio only streams

**Comment by whoamikyo** [comment]
although it is not possible to download only the audio stream, would you be able to download the entire episode, extract the audio stream and merge? currently i have to download the version with audio in japanese and then download the dubbed version, extract the dubbed audio and merge into the main file, if you could automate this process it would be excellent.
