### ISSUE TITLE
Bad Captcha

### ISSUE THREAD

**Issue by storm134** [anidl/crunchyroll-downloader-nx#19]
D:\Drivers\crunchyroll-downloader-nx-master>npm i
audited 420 packages in 2.846s

13 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

D:\Drivers\crunchyroll-downloader-nx-master>node crunchy.js --auth

=== Crunchyroll Downloader NX 4.19.0 ===

[INFO] Authentication
[Q] LOGIN/EMAIL: email
[Q] PASSWORD   : Password
[ERROR] HTTPError 500: Internal Server Error
[ERROR] Authentication failed!
[AUTH] Body: Bad captcha. Please resubmit.

**Comment by storm134** [comment]
updated node to v14.8.0 - no change

**Comment by Stesmus** [comment]
Same problem. Apparently because of frequent requests, there is a block on the IP for a time when requests from my network stop coming.

Is it planned to be able to use external cookies (JSON or Netscape) like youtube-dl does?

**Comment by storm134** [comment]
tried on fresh re-installed windows 10 machine and still getting the same error. anyone else having this issue.

**Comment by bgette** [comment]
try with VPN
if it still dosntt work, i(ll give u another method with "editThisCookie" (extension) that worked when it did this to me a long time ago..

**Comment by storm134** [comment]
thanks bgette vpn worked, which is wierd, if you wouldn't mind i would like to try with editthiscookie if you could send me the method

**Comment by bgette** [comment]
contact me on Telegram : @SalutGrosBg

**Comment by anidl** [comment]
added
