### ISSUE TITLE
[BUG] Can't download subtitles

### ISSUE THREAD

**Issue by OgnistyPoland** [anidl/crunchyroll-downloader-nx#2]
** Main info: **

Script version: 4.15.1
Show ID: 25091
Episode ID: 12

** Additional Info: **
Requesting: [792618] A Certain Scientific Railgun T - 12 - Exterior
[INFO] PAGE MSGs:
  [NAG] Check out the new teaser for the upcoming summer action series The God of High School and learn more about the staff and cast behind the series here!
[ERROR] No available full raw stream! Only clip streams available.
[INFO] Downloading subtitles...
[INFO] Trying get subtitles in old format...
(node:8280) UnhandledPromiseRejectionWarning: Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (zlib.js:180:17)
    at processChunkSync (zlib.js:426:12)
    at zlibBufferSync (zlib.js:166:12)
    at Object.syncBufferWrapper [as unzipSync] (zlib.js:762:14)
    at doDecrypt (D:\POBIERAJKI\CR-v2\modules\module.crunchySubs.js:36:17)
    at Object.decrypt (D:\POBIERAJKI\CR-v2\modules\module.crunchySubs.js:47:30)
    at getMedia (D:\POBIERAJKI\CR-v2\crunchy.js:985:63)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getShowById (D:\POBIERAJKI\CR-v2\crunchy.js:640:13)
(node:8280) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8280) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by anidl** [comment]
Crunchyroll's subtitles old format is broken for now, they changed encryption. This affects even Youtube-DL

https://github.com/ytdl-org/youtube-dl/issues/24900

**Comment by storm134** [comment]
i have been getting this error for a little while, if i re-auth it then works

**Comment by anidl** [comment]
closed due unactivity
