### ISSUE TITLE
[BUG] Proxy connection is not being used in search..

### ISSUE THREAD

**Issue by Abu3safeer** [anidl/crunchyroll-downloader-nx#24]
** Main info: **

Script version: 4.20.0
Show ID: Search
Episode ID: Search

** Additional Info: **

I use crunchy --search2 "TITLE_HERE"
but it returns [ERROR] HTTPError 403: Forbidden

![image](https://user-images.githubusercontent.com/12091003/94633908-51e33100-02d7-11eb-9096-2d4b90429239.png)

I try this:
crunchy --proxy "http://domain:port" --search2 "TITLE_HERE"
but it returns the same thing: [ERROR] HTTPError 403: Forbidden

I use [Charles proxy](https://www.charlesproxy.com/) to make my computer as proxy, I choose Charles because it shows this message when a new connection come:
![image](https://user-images.githubusercontent.com/12091003/94634165-f8c7cd00-02d7-11eb-9d99-93134691be52.png)

So if crunchyroll-downloader-nx will use the proxy, a message should appear, but nothing happened, it is like crunchyroll-downloader-nx does not use the proxy.

**Comment by anidl** [comment]
Proxy not supported right now
