### ISSUE TITLE
Can't download this EP

### ISSUE THREAD

**Issue by Zeniitsu** [anidl/crunchyroll-downloader-nx#26]
the episode work normally on crunchyroll website but can't download it using crunchyroll-downloader-nx-4.20.0-win64

-----

@ C:\Users\Administrator\Desktop\crunchyroll-downloader-nx-4.20.0-win64

> crunchy.exe node crunchy -s 22701 -e m694155

=== Crunchyroll Downloader NX 4.20.0 ===

[INFO] Cookies were updated! (etp_rt)

[S:22701] Noblesse: Awakening
  [S001|694157] PV
   - PremPubDate: 2016-02-04 10:25:36 UTC
   - FreePubDate: 2016-02-04 10:25:36 UTC
  [S002|694155] OVA
   - PremPubDate: 2016-02-04 14:00:00 UTC
   - FreePubDate: 2016-02-04 14:00:00 UTC

[INFO] Selected Episodes: S002

Requesting: [694155] Noblesse: Awakening -  - OVA
[INFO] Cookies were updated! (etp_rt)

[INFO] Your region: US United States of America
[INFO] Your account: ******

[INFO] Selecting raw stream
[ERROR] No available full raw stream! Session expired?
[INFO] Downloading subtitles...
[WARN] Can't find urls for subtitles!

@ C:\Users\Administrator\Desktop\crunchyroll-downloader-nx-4.20.0-win64

>

**Comment by Abu3safeer** [comment]
What is the link?

**Comment by bgette** [comment]
Try `crunchy.exe --auth`

**Comment by Zeniitsu** [comment]
> What is the link?

https://www.crunchyroll.com/noblesse-awakening/noblesse-awakening-ova-694155

**Comment by Zeniitsu** [comment]
> Try `crunchy.exe --auth`

I am already logged in with my premium account.

**Comment by Kanekid2m** [comment]
If its an old stream that does not contain subs you should use the --oldstreams option. That should fix it

**Comment by Kanekid2m** [comment]
`crunchy -s 22701 -e m694155 -q 1080p --oldstreams`

This should do it 💯

**Comment by Zeniitsu** [comment]
> `crunchy -s 22701 -e m694155 -q 1080p --oldstreams`
> 
> This should do it 💯

It worked 💯
