### ISSUE TITLE
Error parsing [4.21.0 beta 1]

### ISSUE THREAD

**Issue by Stesmus** [anidl/crunchyroll-downloader-nx#27]
=== CMD ===

\crunchyroll-downloader-nx v4.21.0 beta 1 -x64->crunchy --help
internal/modules/cjs/loader.js:282
    throw e;
    ^

SyntaxError: Error parsing \crunchyroll-downloader-nx v4.21.0 beta 1 -x64-\package.json: Unexpected end of JSON input
    at parse (<anonymous>)
[90m    at readPackage (internal/modules/cjs/loader.js:270:20)[39m
[90m    at readPackageScope (internal/modules/cjs/loader.js:295:19)[39m
[90m    at shouldUseESMLoader (internal/modules/run_main.js:36:15)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:66:24)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  path: [32m'\\crunchyroll-downloader-nx v4.21.0 beta 1 -x64-\\package.json'[39m
}

\crunchyroll-downloader-nx v4.21.0 beta 1 -x64->crunchy.exe --help
internal/modules/cjs/loader.js:282
    throw e;
    ^

SyntaxError: Error parsing \crunchyroll-downloader-nx v4.21.0 beta 1 -x64-\package.json: Unexpected end of JSON input
    at parse (<anonymous>)
[90m    at readPackage (internal/modules/cjs/loader.js:270:20)[39m
[90m    at readPackageScope (internal/modules/cjs/loader.js:295:19)[39m
[90m    at shouldUseESMLoader (internal/modules/run_main.js:36:15)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:66:24)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  path: [32m'\\crunchyroll-downloader-nx v4.21.0 beta 1 -x64-\\package.json'[39m
}

\crunchyroll-downloader-nx v4.21.0 beta 1 -x64->crunchy --search "Anything"
internal/modules/cjs/loader.js:282
    throw e;
    ^

SyntaxError: Error parsing \crunchyroll-downloader-nx v4.21.0 beta 1 -x64-\package.json: Unexpected end of JSON input
    at parse (<anonymous>)
[90m    at readPackage (internal/modules/cjs/loader.js:270:20)[39m
[90m    at readPackageScope (internal/modules/cjs/loader.js:295:19)[39m
[90m    at shouldUseESMLoader (internal/modules/run_main.js:36:15)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:66:24)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  path: [32m'\\crunchyroll-downloader-nx v4.21.0 beta 1 -x64-\\package.json'[39m
}

**Comment by anidl** [comment]
update to beta 2
