### ISSUE TITLE
Can't download one anime

### ISSUE THREAD

**Issue by OgnistyPoland** [anidl/crunchyroll-downloader-nx#38]
22701

Requesting: [694155] Noblesse: Awakening -  - OVA
[INFO] Selecting raw stream
[ERROR] No available full raw stream! Session expired?
[INFO] Downloading subtitles...
[WARN] Can't find urls for subtitles!

**Comment by bgette** [comment]
Try to reconnect

**Comment by OgnistyPoland** [comment]
Doesn't work

**Comment by izu-co** [comment]
Can you update me whether this issue still exists?

If so, please open a new issue or reopen this one.

**Comment by OgnistyPoland** [comment]
![image](https://user-images.githubusercontent.com/32206254/129383186-16d0fde7-7ada-4f09-bf1d-0a374941c8bc.png)

**Comment by izu-co** [comment]
Is it possible that it is related to your region?

**Comment by OgnistyPoland** [comment]
I can watch it on crunchyroll, so dont think so

**Comment by izu-co** [comment]
@OgnistyPoland Anidl has taken a look and recommands that you use the `--hslang enUS` tag.

Hit me up with the results after your try.

**Comment by izu-co** [comment]
All issues prior to `v5.0.0` will be closed. For more information, please referee to [this](https://github.com/anidl/crunchyroll-downloader-nx/releases/tag/5.0.0) under the `Bug Fixes` Section.
