### ISSUE TITLE
[BUG] Error when downloading multiple episodes

### ISSUE THREAD

**Issue by jdcox215** [anidl/crunchyroll-downloader-nx#39]
** Main info: **

Script version: 4.23.1
Show ID: 23793
Episode ID: 123-170

** Additional Info: **

I get this error when trying to download these Black Clover episodes. I have the latest script version, the latest mkvmerge, ffmpeg, and I'm using the binary on Windows 10

[INFO] Selected Episodes: 0123, 0124, 0125, 0126, 0127, 0128, 0129, 0130, 0131, 0132, 0133, 0134, 0135, 0136, 0137, 0138, 0139, 0140, 0141, 0142, 0143, 0144, 0145, 0146, 0147, 0148, 0149, 0150, 0151, 0152, 0153, 0154, 0155, 0156, 0157, 0158, 0159, 0160, 0161, 0162, 0163, 0164, 0165, 0166, 0167, 0168, 0169, 0170

Requesting: [792259] Black Clover - 123 - Nero Reminisces... Part One
(node:7636) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at getMedia (C:\snapshot\crunchyroll-downloader-nx\crunchy.js)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getShowById (C:\snapshot\crunchyroll-downloader-nx\crunchy.js)
    at async C:\snapshot\crunchyroll-downloader-nx\crunchy.js
(Use `crunchy --trace-warnings ...` to show where the warning was created)
(node:7636) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7636) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bobbers0n** [comment]
I've noticed this issue as well. I've my own copy, and it seems that it happens at https://github.com/anidl/crunchyroll-downloader-nx/blob/0955d1db8387879c8f85611d0ee66067b6722fe3/crunchy.js#L580 
Crunchyroll doesn't recognize/support the "browser" request and thus the regex can't match. Using different user agents doesn't seem to work either (I tried multiple)

**Comment by OryWareKyrie** [comment]
I have the same problem but...
```
[INFO] Selected Episodes: 0001

Requesting: [799069] JUJUTSU KAISEN (Portuguese Dub) - 1 - Ryoumen Sukuna
(node:8684) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at getMedia (C:\snapshot\crunchyroll-downloader-nx\crunchy.js)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getShowById (C:\snapshot\crunchyroll-downloader-nx\crunchy.js)
    at async C:\snapshot\crunchyroll-downloader-nx\crunchy.js
(Use `crunchy --trace-warnings ...` to show where the warning was created)
(node:8684) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8684) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by izu-co** [comment]
Is this still an issue?

**Comment by izu-co** [comment]
All issues prior to `v5.0.0` will be closed. For more information, please referee to [this](https://github.com/anidl/crunchyroll-downloader-nx/releases/tag/5.0.0) under the `Bug Fixes` Section.
