### ISSUE TITLE
[BUG] not able to execute the script

### ISSUE THREAD

**Issue by Kanekid2m** [anidl/crunchyroll-downloader-nx#4]
** Main info: **

Script version:  4.17.0 stable 
Show ID: 
Episode ID: 

** Additional Info: **

I am sure that I installed all requirements and some of them I had already because I use another scripts. When I try to execute the command node crunchy I get this error 

`internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'C:\Users\Administrator\Downloads\crunchuroll-download
er-nx-4.17.0-win64\crunchyroll-downloader-nx-4.17.0-win64\crunchy'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966
:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:842:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_ma
in.js:71:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}
`
I tried to read and know where the error is but I do not seem to know whats wrong and why I am not able to run it. I hope you can explain to me what the issue is. I am on Windows Server 2012 btw.

**Comment by bgette** [comment]
I had the same problem, since then,
I use (source code .zip) version & I dont have any more
try with https://github.com/anidl/crunchyroll-downloader-nx/archive/4.17.0.zip, maybe that solve the problem

**Comment by Kanekid2m** [comment]
> 
> 
> I had the same problem, since then,
> I use (source code .zip) version & I dont have any more
> try with https://github.com/anidl/crunchyroll-downloader-nx/archive/4.17.0.zip, maybe that solve the problem


ty it works now! but looks like the script itself is not working because of cloudfare protection. when I try to login I get the error captcha could not be solved. I hope they fix it soon

**Comment by bgette** [comment]
The problem of cloudflare also on ytb-dl, and other CR-downloader.
a few persons have already fix this
i hope anidl to

**Comment by anidl** [comment]
For binary build just use "crunchy -s 123" without "node"
