### ISSUE TITLE
To Love Ru [BUG] 

### ISSUE THREAD

**Issue by Adeleine** [anidl/crunchyroll-downloader-nx#40]
https://www.crunchyroll.com/to-love-ru?skip_wall=1

crunchy.exe --search "to love ru"

=== Crunchyroll Downloader NX 4.21.0-beta.2 ===

[INFO] Nothing Found!

**Comment by bgette** [comment]
try with -g "to love ru" or To-Love ru"

**Comment by Adeleine** [comment]
I tried both but it displays the message below. It doesn't show the results, so I don't know what the show id is.

crunchy.exe --search2 "To-Love ru"

=== Crunchyroll Downloader NX 4.23.1 ===

[INFO] Displaying results from 1 - 24 out of 78

crunchyroll-downloader-nx-4.23.1-win64>

**Comment by izu-co** [comment]
Is this still an issue?

**Comment by izu-co** [comment]
This is no issue with the script. The show you are trying to download has an age limit.
