### ISSUE TITLE
[BUG] HTTPError 403: Forbidden

### ISSUE THREAD

**Issue by dogoterra** [anidl/crunchyroll-downloader-nx#41]
** Main info: **

=== Crunchyroll Downloader NX 4.23.1 ===

[INFO] Selected media: 810095

Requesting: [810095] ...
[ERROR] HTTPError 403: Forbidden
[ERROR] Attention Required! | Cloudflare
[ERROR] Failed to get video page!

Script version: 4.23.1
Episode ID: 810095

**Comment by bgette** [comment]
your command?

**Comment by dogoterra** [comment]
node crunchy.js --e m810095

**Comment by bgette** [comment]
try -e

**Comment by dogoterra** [comment]
same error :(

**Comment by izu-co** [comment]
Can you try to reauth?

**Comment by izu-co** [comment]
All issues prior to `v5.0.0` will be closed. For more information, please referee to [this](https://github.com/anidl/crunchyroll-downloader-nx/releases/tag/5.0.0) under the `Bug Fixes` Section.
