### ISSUE TITLE
HTTPError 403: Forbidden

### ISSUE THREAD

**Issue by Jotaro-San** [anidl/crunchyroll-downloader-nx#42]
** Main info: **

node crunchy -s 25359 -e m801518

=== Crunchyroll Downloader NX 4.23.1 ===

[ERROR] HTTPError 403: Forbidden
[ERROR] Attention Required! | Cloudflare

Script version: 4.23.1
Show ID: 25359
Episode ID: 801518

** Additional Info: **
I'm using a premium CR account and I encountered this problem recently.
Everything was work fine last season, but after the release of spring animes i faced this probem "HTTPError 403: Forbidden" a lot of times.

**Comment by Jotaro-San** [comment]
sorry, maybe the problem was from me.
everything work fine

**Comment by bgette** [comment]
how you solve this?
