### ISSUE TITLE
[BUG] UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by xVoldx** [anidl/crunchyroll-downloader-nx#43]
** Main info: **

Script version: 4.23.1
Show ID:  23333
Episode ID: 182

** Additional Info: **

Requesting: [801743] BORUTO: NARUTO NEXT GENERATIONS - 182 - Ao
(node:6505) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at getMedia (/content/crunchyroll-downloader-nx/crunchy.js:587:47)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getShowById (/content/crunchyroll-downloader-nx/crunchy.js:530:13)
    at async /content/crunchyroll-downloader-nx/crunchy.js:111:9
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6505) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6505) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by espher90** [comment]
I recently encountered this error too. Not too sure what is happening. Could it be related to our IP addresses?
