### ISSUE TITLE
Download subtitles in multiple Languages

### ISSUE THREAD

**Issue by Pfuenzle** [anidl/crunchyroll-downloader-nx#44]
Is it possible to download multiple subtitles with specific languages?
I tried to download a series with enUS, reRU and deDE, but with 
`--dlsubs "deDE" --dlsubs "enUS --dlsubs "ruRU""`,
only the deDE subtitles get downloaded.
I also tried to do
`--dlsubs "deDE, enUS, ruRU"`,
but this doesnt work at all

**Comment by narutojawad** [comment]
I don't know if it's possible that way.
you may use "All" to download all subs tho.
alternatively, you could make a batch file with each language you want
just copy this into a .bat file and run it :)
@echo off
set /p S="Enter the name of the Anime (Copy ID):"
crunchy -f %S%
set /p N="Enter Series ID:"
set /p E="Enter episode number/s:"
crunchy -s %N% -e %E% --skipdl --dlsubs deDE
crunchy -s %N% -e %E% --skipdl --dlsubs enUS
crunchy -s %N% -e %E% --skipdl --dlsubs ruRU
pause

Note: you may remove the first two lines if you don't want to search every time you use it.
"set /p S="Enter the name of the Anime (Copy ID):"
crunchy -f %S%"

**Comment by izu-co** [comment]
I would assume that this issue has resolved itself?

**Comment by Pfuenzle** [comment]
The script Narutojawad posted was very helpful, thanks for that,
but it still would be great if it would be possible to just give multiple --dlsubs parameters and the program muxes all the subs into one file.
Would be really great if you would be willing to implement that. 
From what I've seen, the program uses a ".json" to tell what should be muxed, so the additional Subtitles should "only" be downloaded in a loop and then be added to the .json and it should work.

Thanks a lot
