### ISSUE TITLE
[BUG] TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by espher90** [anidl/crunchyroll-downloader-nx#48]
This only happens when I use a VPN. I use hide.me VPN to connect to the US.  After I encounter this bug, if I disable my VPN then use the program, I get the same error. I have to delete everything and go through the setup process again if I want it to work again. This only happened recently. It was working just fine with the VPN on before. What can I do to resolve this?

Script version: Not sure where to find that, the latest if I were to guess
Show ID: 25234, but not limited
Episode ID: 801615, again not limited

** Additional Info: **
The following is the entire transcript.

`[INFO] Cookies were updated! (etp_rt, c_visitor, session_id)

[INFO] Authentication successful!

C:\Users\wease\Downloads\crunchyroll-downloader-nx-master\crunchyroll-downloader-nx-master>node crunchy --search jujutsu kaisen

=== Crunchyroll Downloader NX 4.23.1 ===

[INFO] Search Results:
[SERIES] #279979 JUJUTSU KAISEN
  [S:25234] JUJUTSU KAISEN
  [S:25274] JUJUTSU KAISEN (German Dub)
  [S:25275] JUJUTSU KAISEN (French Dub)
  [S:25276] JUJUTSU KAISEN (Portuguese Dub)
  [S:25277] JUJUTSU KAISEN (Spanish Dub)
  [S:25278] JUJUTSU KAISEN (English Dub)

[INFO] Total results: 1

C:\Users\wease\Downloads\crunchyroll-downloader-nx-master\crunchyroll-downloader-nx-master>node crunchy -s 25234 -e 22 -q 240p --sub --mks

=== Crunchyroll Downloader NX 4.23.1 ===

[S:25234] JUJUTSU KAISEN
  [0024|801617] 24 - Accomplices
   - FreePubDate: 2021-04-02 17:45:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0023|801616] 23 - The Origin of Blind Obedience - 2 -
   - FreePubDate: 2021-03-26 17:45:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0022|801615] 22 - The Origin of Blind Obedience
   - FreePubDate: 2021-03-19 17:45:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0021|801614] 21 - Jujutsu Koshien
   - FreePubDate: 2021-03-12 18:45:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0020|801613] 20 - Nonstandard
   - FreePubDate: 2021-03-05 18:45:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0019|801612] 19 - Black Flash
   - FreePubDate: 2021-02-26 18:45:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0018|801611] 18 - Sage
   - FreePubDate: 2021-02-19 18:45:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0017|801610] 17 - Kyoto Sister School Exchange Event - Group Battle 3 -
   - FreePubDate: 2021-02-12 18:45:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0016|801609] 16 - Kyoto Sister School Exchange Event - Group Battle 2 -
   - FreePubDate: 2021-02-05 18:45:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0015|801608] 15 - Kyoto Sister School Exchange Event - Group Battle 1 -
   - FreePubDate: 2021-01-29 18:45:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0014|801607] 14 - Kyoto Sister School Exchange Event - Group Battle 0 -
   - FreePubDate: 2021-01-22 18:45:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0013|797877] 13 - Tomorrow
   - FreePubDate: 2021-01-01 18:45:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0012|797876] 12 - To You, Someday
   - FreePubDate: 2020-12-25 18:45:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0011|797875] 11 - Narrow-minded
   - FreePubDate: 2020-12-18 18:45:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0010|797874] 10 - Idle Transfiguration
   - FreePubDate: 2020-12-11 18:45:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0009|797873] 9 - Small Fry and Reverse Retribution
   - FreePubDate: 2020-12-04 18:45:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0008|797872] 8 - Boredom
   - FreePubDate: 2020-11-27 18:45:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0007|797871] 7 - Assault
   - FreePubDate: 2020-11-20 18:45:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0006|797870] 6 - After Rain
   - FreePubDate: 2020-11-13 18:45:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0005|797869] 5 - Curse Womb Must Die -II-
   - FreePubDate: 2020-11-06 18:45:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0004|797868] 4 - Curse Womb Must Die
   - FreePubDate: 2020-10-30 17:45:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0003|797867] 3 - Girl of Steel
   - FreePubDate: 2020-10-23 17:45:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0002|797866] 2 - For Myself
   - FreePubDate: 2020-10-16 17:45:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU
  [0001|797865] 1 - Ryomen Sukuna
   - FreePubDate: 2020-10-09 17:45:00 UTC
   - Subtitles: enUS, esLA, esES, frFR, ptBR, arME, itIT, deDE, ruRU

[INFO] Selected Episodes: 0022

Requesting: [801615] JUJUTSU KAISEN - 22 - The Origin of Blind Obedience
C:\Users\wease\Downloads\crunchyroll-downloader-nx-master\crunchyroll-downloader-nx-master\crunchy.js:587
    const contextJson = JSON.parse(contextData[1]);
                                              ^

TypeError: Cannot read property '1' of null
    at getMedia (C:\Users\wease\Downloads\crunchyroll-downloader-nx-master\crunchyroll-downloader-nx-master\crunchy.js:587:47)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getShowById (C:\Users\wease\Downloads\crunchyroll-downloader-nx-master\crunchyroll-downloader-nx-master\crunchy.js:530:13)
    at async C:\Users\wease\Downloads\crunchyroll-downloader-nx-master\crunchyroll-downloader-nx-master\crunchy.js:111:9

C:\Users\wease\Downloads\crunchyroll-downloader-nx-master\crunchyroll-downloader-nx-master>`

**Comment by espher90** [comment]
BTW, I'm using the master files.

**Comment by Golumpa** [comment]
This app will no longer work inside the US, with a US VPN, US Linux server, etc. Crunchy roll has started enforcing users inside the US to use their beta website (beta.crunchyroll.com) which is basically a backend clone of their parent companies other service VRV. You can tell this as if you use the beta site, you can literally replace the beta.crunchyroll.com domain to vrv.co and it'll still work.

Until this app is updated, and it's going to need a massive overhaul of the way the app handles the API. This will not be able to be used with any IP inside of the US.

**Comment by espher90** [comment]
@Golumpa Thank you for your response. I guess this will take some time to resolve. But until then, are there any solutions available? Such as changing the cookies?

**Comment by Golumpa** [comment]
@espher90 You can try using a VPN location not in the US that isn't also blocked by crunchy. Any IP you use that's based in the US will be redirected to the beta site and API. My only guess would be to use a VPN in another country, even then it might not work. It's your best bet for now.

**Comment by Oujiii** [comment]
For me personally this hasn't been working for a while now, even before Crunchyroll Beta. One should be assume Crunchyroll Beta will be permanent everywhere on a few weeks, they are probably finishing translating it. On my country you can opt out of it and stay there for a while, but if you login on another country, anytime I login back to my country it is back on Beta, this is going to be tricky. Might be the time to start looking for tools that take stuff out of VRV (which as of right now has Hidive too, so it's a bonus).
