### ISSUE TITLE
Cannot get custom cookies to load

### ISSUE THREAD

**Issue by jorgen639** [anidl/crunchyroll-downloader-nx#49]
Before I ask for help regarding this, does loading custom cookies work the same way as a VPN would if I wanted to download a show unavailable in my area? I got my cookies from my US Crunchyroll session from EditThisCookie. I exported it, put it in a text file named cookies.txt, then pasted it into the config folder. After I authenticate, I would get an error saying it couldn't load `cookie.txt`. It was a bit weird since I checked that I had an s at the end of the name.

**Comment by izu-co** [comment]
`cookie.txt` refers to the `cookies.txt` file.

Can you give me a visual on the file structure as well as the `cookies.txt` file (make sure to censor sensitive content)?

**Comment by izu-co** [comment]
The spelling issue has been resolved in the latest release

**Comment by izu-co** [comment]
All issues prior to `v5.0.0` will be closed. For more information, please referee to [this](https://github.com/anidl/crunchyroll-downloader-nx/releases/tag/5.0.0) under the `Bug Fixes` Section.
