### ISSUE TITLE
[ERROR] Cannot read property '1' of null

### ISSUE THREAD

**Issue by Cl1ntfordev** [anidl/crunchyroll-downloader-nx#52]
![image](https://user-images.githubusercontent.com/88973954/129480315-5d4bd817-cb6d-46c5-9d89-588ab3d3c76c.png)

node crunchy -s 24588 -e 1-12 -q 720p --tsparts --dub "por" --filename "{title} - {ep_num}"

**Comment by Anit0** [comment]
@Cl1ntfordev  

just change beta to classic it's fixed. from your cr account.

**Comment by izu-co** [comment]
Jep it seems like the beta API does not work.

**Comment by narutojawad** [comment]
I get this exact message when I try to download One Piece "ID: 21369" 
This error only show up when downloading one piece for some reason!
I don't use VPN or Beta.

**Comment by kokoboko5** [comment]
> I get this exact message when I try to download One Piece "ID: 21369"
> This error only show up when downloading one piece for some reason!
> I don't use VPN or Beta.
> 
> BTW when I do a search This Arc "21369" [Wano Kuni] doesn't show up, I Only get this:
> 
> [SERIES] #257631 One Piece (2013)
> [S:21685] One Piece: East Blue (1-61)
> [S:21687] One Piece: Alabasta (62-135)
> [S:21689] One Piece: Sky Island (136-206)
> [S:21691] One Piece: Water 7 (207-325)
> [S:21695] One Piece: Thriller Bark (326-384)
> [S:21697] One Piece: Summit War (385-516)
> [S:21825] One Piece: Fishman Island (517-574)
> [S:22673] One Piece: Punk Hazard (575-629)
> [S:22675] One Piece: Dressrosa (630-699)
> [S:23719] One Piece: Dressrosa (700-746)
> 
> Even though it's available in the website.

I am also getting the same error

**Comment by izu-co** [comment]
Can you check if the app is trying to log you out of the beta version? If not, try the newest version.

**Comment by izu-co** [comment]
All issues prior to `v5.0.0` will be closed. For more information, please referee to [this](https://github.com/anidl/crunchyroll-downloader-nx/releases/tag/5.0.0) under the `Bug Fixes` Section.
