### ISSUE TITLE
[BUG] UnhandledPromiseRejectionWarning: TypeError: Cannot write private member to an object whose class did not declare it

### ISSUE THREAD

**Issue by manifesto1** [anidl/crunchyroll-downloader-nx#53]
![image](https://user-images.githubusercontent.com/85753037/130305233-edfdf011-8bfc-45a3-996a-127db2102e79.png)

**Comment by bgette** [comment]
if you wanna see the help -h

**Comment by izu-co** [comment]
Fixed in the newest commit. Will be included with the next major update into the binarys.
