### ISSUE TITLE
[BUG] I can't do anything...

### ISSUE THREAD

**Issue by bgette** [anidl/crunchyroll-downloader-nx#54]
** Main info: **

Script version: 5.0.0 (last version)
Show ID: anyID
Episode ID: anyEP

** Additional Info: **
when I wanna `node crunchy --auth` for example, he show me the -h, same when i wanna download all fonts from `--dlfonts`
![image](https://user-images.githubusercontent.com/64483377/131581286-387ddaf5-0dd5-4e25-9f55-8ca7accf3f45.png)

**Comment by izu-co** [comment]
Can you show me the full console log, please? Is there any notice at the bottom, maybe missing arguments?

**Comment by bgette** [comment]
![image](https://user-images.githubusercontent.com/64483377/131589439-9a00bc9e-b13d-4ce8-b7a3-baa17ca50612.png)

**Comment by XxUnkn0wnxX** [comment]
same issue
https://user-images.githubusercontent.com/2242880/131616715-8ef10da6-d72e-4cfb-b446-4d186a147aa6.mp4

**Comment by izu-co** [comment]
Yeah noticed it. Working on it!

**Comment by izu-co** [comment]
Please try the newest release

**Comment by bgette** [comment]
it works but is it possible to readd the "datepremium"
(last version)
![image](https://user-images.githubusercontent.com/64483377/131667399-576d4673-a1c0-448b-bbb2-3e2dc5075b8f.png)
(old version)
![image](https://user-images.githubusercontent.com/64483377/131667551-2f4d7294-5e52-4f2f-9b29-e0da9aad7b62.png)

**Comment by izu-co** [comment]
It is always hidden if it is already here.

**Comment by bgette** [comment]
you plan to fix the proxy?

**Comment by izu-co** [comment]
More or less. Just fixed it in the hls-downloader module, which downloads the streams.

**Comment by bgette** [comment]
btw can you check your e-mail?
