### ISSUE TITLE
BCP Mkvmerge

### ISSUE THREAD

**Issue by STRATOS99K** [anidl/crunchyroll-downloader-nx#57]
As it is now, using --bcp while using mkvmerge will only add es-419 and pt-BR just 2 tracks.
            const langArg = options.useBCP ? t.language.locale : t.language.code;
Is using t.language.locale the actual codes for most are at cr_locale in module.langsDATA.js, I would change locale with the same info on cr_locale and for the arabic tracks ar-SA for both on locale.

Related, when muxing I see that for the track names we get pt (BR) / Português (Brasil) eg, could we  have english names for the tracks before the / so it would look like
English / English (US)
Spanish (Latin American) / Español (América Latina)
Portuguese (Brazilian) / Português (Brasil)

instead of 
en / English (US)
es (419) / Español (América Latina)
pt (BR) / Português (Brasil)

If the current behavior for the muxing is intended then please close this ticket.

**Comment by izu-co** [comment]
Which version of Mkvmerge do you use?

**Comment by STRATOS99K** [comment]
> Which version of Mkvmerge do you use?

57.0.0.0 for windows

**Comment by OryWareKyrie** [comment]
@STRATOS99K in my opinion I think it's unnecessary to use this in the title 
> Text
ID                          : 3
Format                      : ASS
Codec ID                    : S_TEXT/ASS
Codec ID/Info               : Advanced Sub Station Alpha
Duration                    : 3 s 40 ms
Bit rate                    : 278 b/s
Count of elements           : 1
Compression mode            : Lossless
Stream size                 : 106 Bytes (0%)
Title                       : Portuguese (Brazilian) / Português (Brasil)
Language                    : Portuguese
Default                     : Yes
Forced                      : No

I prefer that

> ID                          : 3
Format                      : ASS
Codec ID                    : S_TEXT/ASS
Codec ID/Info               : Advanced Sub Station Alpha
Duration                    : 3 s 40 ms
Bit rate                    : 278 b/s
Count of elements           : 1
Compression mode            : Lossless
Stream size                 : 106 Bytes (0%)
Title                       : Portuguese (Brazilian)
Language                    : Portuguese
Default                     : Yes
Forced                      : No

or like this

> ID                          : 3
Format                      : ASS
Codec ID                    : S_TEXT/ASS
Codec ID/Info               : Advanced Sub Station Alpha
Duration                    : 3 s 40 ms
Bit rate                    : 278 b/s
Count of elements           : 1
Compression mode            : Lossless
Stream size                 : 106 Bytes (0%)
Title                       : Português (Brasil)
Language                    : Portuguese
Default                     : Yes
Forced                      : No

**Comment by izu-co** [comment]
As long as the language is right (in which language it may be) I see no problem.

**Comment by OryWareKyrie** [comment]
> As long as the language is right (in which language it may be) I see no problem.

I went out tinkering with the code and I only managed to put `Português (Brasil)` I don't know how to do it to `Portuguese (Brazilian) / Português (Brasil)`

**Comment by izu-co** [comment]
You can download only audio with `--dub` or what do you mean?

**Comment by STRATOS99K** [comment]
The new changes look great to me, thank you!
