### ISSUE TITLE
Anime not found by search!

### ISSUE THREAD

**Issue by arbarbosa1979** [anidl/crunchyroll-downloader-nx#59]
I tested if that series "**My Bride is a Mermaid**" was found by search, but neither option I find anything. I redo the login about 4 times and it had no positive effect.

I can access this anime through the website, so the problem is not whether it's premium or not.

Brazil: `https://www.crunchyroll.com/pt-br/my-bride-is-a-mermaid`

```
> crunchy --auth

=== Crunchyroll Downloader NX 5.1.2 ===

[INFO] Authentication
[Q] LOGIN/EMAIL: ****************
[Q] PASSWORD   : *****************
[INFO] Cookies were updated! (c_visitor, session_id)

[INFO] Cookies were updated! (etp_rt)

[INFO] Authentication successful!

@ D:\Crunchyroll Downloader

> crunchy -f "My Bride is a Mermaid"

=== Crunchyroll Downloader NX 5.1.2 ===

[INFO] Nothing Found!

> crunchy -g "My Bride is a Mermaid"

=== Crunchyroll Downloader NX 5.1.2 ===

[INFO] NOTHING FOUND!

@ D:\Crunchyroll Downloader
```

**Comment by levaculik2** [comment]
I tested it here too and actually when you put ./crunchy --search "My Bride is a Mermaid" it doesn't show anything related and the funniest thing on the site has the anime there.it only appears if you change the language from english to brazilian portuguese. But if you use ./crunchy-beta --search "My Bride is a Mermaid" the anime even appears for example:
./crunchy-beta -s GYE5M298R -q "1080p" --dub "jpn" --dlsubs "all" --mp4mux

[ERROR] HTTPError 404: Not Found
[ERROR] Show Request FAILED!

**Comment by izu-co** [comment]
@arbarbosa1979 Please see the newest release and follow the instructions to change the search region.
@levaculik2 you need to use season id, not series id

crunchy-beta --srz GYE5M298R
crunchy-beta -s GR7510WZY

Z:GYE5M298R -- Series ID
S:GR7510WZY -- Season ID

**Comment by arbarbosa1979** [comment]
Tested and problem solved, many thanks for the good work.
