### ISSUE TITLE
allSub and allDub Commands

### ISSUE THREAD

**Issue by WeetbixNMilk** [anidl/crunchyroll-downloader-nx#65]
Hey,
In your other similar program, funimation-downloader-nx; I regularly use the command --allSubs --allDubs. I know the command for --dlsubs does all subtitles but is there an equivalent for all dub languages. It's handy having mkvmerge put all the subtitles, audio tracks and video in a single container rather than 2 different sources.
Cheers.

**Comment by izu-co** [comment]
Since the way crunchy works, the implementation is not that easy to realize.
