### ISSUE TITLE
Impossible to download One Piece episodes with crunchy.js

### ISSUE THREAD

**Issue by Gaby13627** [anidl/crunchyroll-downloader-nx#73]
Hello,

I'm trying to download One Piece episodes with the classic version using the code at the end of the link of an episode, but it doesn't work. It works perfectly for the other series. I get this in my cmd when running :

```
node crunchy.js -e m816837

=== Crunchyroll Downloader NX 5.3.1 ===

[INFO] Selected media: 816837

[INFO] Requesting: [816837] ...

[INFO] PAGE MSGs:
  [ERROR] Empty message

[ERROR] Something goes wrong...

```
Link of the episode used in this example :
https://www.crunchyroll.com/fr/one-piece/episode-995-raid-inheriting-odens-will-816837

I have to go through crunchy-beta.js but it's a bit more constraining for me to get the beta ids of the episodes . Is it because of my location (France)? Would there be a solution to use the normal version of crunchyroll-nx earlier than the beta?

[Info] I have a Crunchyroll premium account and functional .

Thank's for your help.

**Comment by izu-co** [comment]
This tool is discontinued. Please use [the multi downloader](https://github.com/anidl/multi-downloader-nx)!
