### ISSUE TITLE
[BUG] --defsublang does not work as expected

### ISSUE THREAD

**Issue by rigoberto32** [anidl/crunchyroll-downloader-nx#77]
** Main info: **

Script version: 
Show ID: https://www.crunchyroll.com/es/fena-pirate-princess
Episode ID: 816893

** Additional Info: **

NOTE: the version of mkvtoolnix and mkvmerge that I have is v62.0.0 "'Apollo"'

the code I use is the following: 
./crunchy -e 816893 -q max --dlsubs=es-419 es en --mks true --defsublang es-419 --filename "{title}.S01E{ep_num}.{suffix}.CR.WEB-DL.AAC2.0.H264" --folder true 

the json code of the muxing is the following:
https://pastebin.com/raw/538rXSdX

In the code you can see that there is the instruction to place the language "es-419" as main, but when I open it with mkvtoolnix all the tracks appear as "predefined" and VLC uses the track "es", others Players use "en", but do not play by default the one of Latin Spanish.

Screenshots of mkvtoolnix indicating that all tracks are predefined, and terminal output:

![Screenshot_20211024-213603~3](https://user-images.githubusercontent.com/91707595/138631338-ac92796f-10af-4c66-a426-cda7debd785c.png)

![Screenshot_20211024-211444~6](https://user-images.githubusercontent.com/91707595/138693117-8fa1c1c2-4b38-4344-872e-474f145a9854.png)

or is this really how it should work and I was expecting something else?

**Comment by izu-co** [comment]
This tool is discontinued. Please use [the multi downloader](https://github.com/anidl/multi-downloader-nx)!
